module.exports = [
  { id: 1, gameId: 1, title: "Going East!" },
  { id: 2, gameId: 1, title: "Halloween Paint Jobs Pack" },
  { id: 3, gameId: 1, title: "Ice Cold Paint Jobs Pack" },
  { id: 4, gameId: 1, title: "Prehistoric Paint Jobs Pack" },
  { id: 5, gameId: 1, title: "Force of Nature Paint Jobs Pack" },
  { id: 6, gameId: 1, title: "Metallic Paint Jobs Pack" },
  { id: 7, gameId: 1, title: "UK Paint Jobs Pack" },
  { id: 8, gameId: 1, title: "Irish Paint Jobs Pack" },
  { id: 9, gameId: 1, title: "Scottish Paint Jobs Pack" },
  { id: 10, gameId: 1, title: "Flip Paint Designs" },
  { id: 11, gameId: 1, title: "Polish Paint Jobs Pack" },
  { id: 12, gameId: 1, title: "Brazilian Paint Jobs Pack" },
  { id: 13, gameId: 1, title: "Fantasy Paint Jobs Pack" },
  { id: 14, gameId: 1, title: "USA Paint Jobs Pack" },
  { id: 15, gameId: 1, title: "Scandinavia" },
  { id: 16, gameId: 1, title: "Canadian Paint Jobs Pack" },
  { id: 17, gameId: 1, title: "High Power Cargo Pack" },
  { id: 18, gameId: 1, title: "German Paint Jobs Pack" },
  { id: 19, gameId: 1, title: "French Paint Jobs Pack" },
  { id: 20, gameId: 1, title: "Czech Paint Jobs Pack" },
  { id: 21, gameId: 1, title: "Christmas Paint Jobs Pack" },
  { id: 22, gameId: 1, title: "Raven Truck Design Pack" },
  { id: 23, gameId: 1, title: "Norwegian Paint Jobs Pack" },
  { id: 24, gameId: 1, title: "Danish Paint Jobs Pack" },
  { id: 25, gameId: 1, title: "Swedish Paint Jobs Pack" },
  { id: 26, gameId: 1, title: "Viking Legends" },
  { id: 27, gameId: 1, title: "Russian Paint Jobs Pack" },
  { id: 28, gameId: 1, title: "Cabin Accessories" },
  { id: 29, gameId: 1, title: "Michelin Fan Pack" },
  { id: 30, gameId: 1, title: "Japanese Paint Jobs Pack" },
  { id: 31, gameId: 1, title: "PC Gamer DLC" },
  { id: 32, gameId: 1, title: "Turkish Paint Jobs Pack" },
  { id: 33, gameId: 1, title: "Wheel Tuning Pack" },
  { id: 34, gameId: 1, title: "Italian Paint Jobs Pack" },
  { id: 35, gameId: 1, title: "SchwarzmГјller Trailer Pack" },
  { id: 36, gameId: 1, title: "Rocket League Promo" },
  { id: 37, gameId: 1, title: "Hungarian Paint Jobs Pack" },
  { id: 38, gameId: 2, title: "Kenworth T680" },
  { id: 39, gameId: 2, title: "Peterbilt 579" },
  { id: 40, gameId: 2, title: "Volvo VNL" },
  { id: 41, gameId: 2, title: "Nevada" },
  { id: 42, gameId: 2, title: "Kenworth W900" },
  { id: 43, gameId: 2, title: "Steampunk Paint Jobs Pack" },
  { id: 44, gameId: 2, title: "Wheel Tuning Pack" },
  { id: 45, gameId: 1, title: "Slovak Paint Jobs Pack" },
  { id: 46, gameId: 1, title: "Spanish Paint Jobs Pack" },
  { id: 47, gameId: 1, title: "Window Flags" },
  { id: 48, gameId: 1, title: "Austrian Paint Jobs Pack" },
  { id: 49, gameId: 1, title: "Mighty Griffin Tuning Pack" },
  { id: 50, gameId: 1, title: "South Korean Paint Jobs Pack" },
  { id: 51, gameId: 1, title: "Swiss Paint Jobs Pack" },
  { id: 52, gameId: 1, title: "Chinese Paint Jobs Pack" },
  { id: 53, gameId: 1, title: "Pirate Paint Jobs Pack" },
  { id: 54, gameId: 1, title: "DAF Tuning Pack" },
  { id: 55, gameId: 2, title: "Arizona" },
  { id: 56, gameId: 2, title: "Steering Creations Pack" },
  { id: 57, gameId: 1, title: "Vive la France !" },
  { id: 58, gameId: 1, title: "Heavy Cargo Pack" },
  { id: 59, gameId: 1, title: "Finnish Paint Jobs Pack" },
  { id: 60, gameId: 1, title: "Belgian Paint Jobs Pack" },
  { id: 61, gameId: 2, title: "Peterbilt 389" },
  { id: 62, gameId: 2, title: "Halloween Paint Jobs Pack" },
  { id: 63, gameId: 1, title: "Dragon Truck Design Pack" },
  { id: 64, gameId: 1, title: "Romanian Paint Jobs Pack" },
  { id: 65, gameId: 1, title: "Australian Paint Jobs Pack" },
  { id: 66, gameId: 1, title: "Valentine's Paint Jobs Pack" },
  { id: 67, gameId: 1, title: "Italia" },
  { id: 68, gameId: 1, title: "Special Transport" },
  { id: 69, gameId: 2, title: "Dragon Truck Design Pack" },
  { id: 70, gameId: 2, title: "Christmas Paint Jobs Pack" },
  { id: 71, gameId: 2, title: "Valentine's Paint Jobs Pack" },
  { id: 72, gameId: 2, title: "Heavy Cargo Pack" },
  { id: 73, gameId: 2, title: "New Mexico" },
  { id: 74, gameId: 2, title: "Oregon" },
  { id: 75, gameId: 1, title: "Portuguese Paint Jobs Pack" },
  { id: 76, gameId: 1, title: "Dutch Paint Jobs Pack" },
  { id: 77, gameId: 1, title: "Beyond the Baltic Sea" },
  { id: 78, gameId: 1, title: "Space Paint Jobs Pack" },
  { id: 79, gameId: 1, title: "Krone Trailer Pack" },
  { id: 80, gameId: 2, title: "Classic Stripes Paint Jobs Pack" },
  { id: 81, gameId: 2, title: "Special Transport" },
  { id: 82, gameId: 1, title: "Estonian Paint Jobs Pack" },
  { id: 83, gameId: 1, title: "Latvian Paint Jobs Pack" },
  { id: 84, gameId: 1, title: "Lithuanian Paint Jobs Pack" },
  { id: 85, gameId: 2, title: "Washington" },
  { id: 86, gameId: 2, title: "Forest Machinery" },
  { id: 87, gameId: 2, title: "Utah" },
  { id: 88, gameId: 2, title: "Space Paint Jobs Pack" },
  { id: 89, gameId: 1, title: "Goodyear Tyres Pack" },
]